# Google App Engine Settings
runtime: nodejs16

instance_class: F2
# env : flex
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10

# Supabase
env_variables:
  NODE_ENV: "production"
  DATABASE_HOST: "db.whkacgsmmzgbsyrsjmxh.supabase.co"
  DATABASE_NAME: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "sEhnybZtq3bnjm@"
# GCP
# env_variables:
#   HOST: '0.0.0.0'
#   NODE_ENV: 'production'
#   DATABASE_NAME: 'strapi'
#   DATABASE_USER: 'postgres'
#   DATABASE_PASSWORD: '<password>'
#   INSTANCE_CONNECTION_NAME: '<instance_identifier>'

# beta_settings:
#   cloud_sql_instances: '<instance_identifier>'
